FROM eclipse-temurin:21-jdk-ubi9-minimal AS build
WORKDIR /app
COPY . .
RUN microdnf install -y wget unzip findutils && \
    wget https://services.gradle.org/distributions/gradle-8.5-bin.zip && \
    unzip gradle-8.5-bin.zip && \
    rm gradle-8.5-bin.zip
ENV PATH="/app/gradle-8.5/bin:${PATH}"
RUN gradle :service:healthcare:bootJar --no-daemon

FROM eclipse-temurin:21-jdk-ubi9-minimal
VOLUME /tmp
COPY --from=build /app/service/healthcare/build/libs/*.jar healthcare-service.jar
ENTRYPOINT ["java", "-jar", "/healthcare-service.jar"]
